version: '3'
services:
  
  app:
    container_name: "warehouse_app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - warehouse_network

  db:
    image: postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    networks:
      - warehouse_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - warehouse_network
    ports:
      - "5050:80"

# lightweigh alternative to pgadmin  
  # adminer:
  #   image: adminer
  #   restart: always
  #   networks:
  #     - warehouse_network
  #   ports:
  #     - 8081:8080
    

networks:
  warehouse_network:
