name: Backend build pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - run: go version

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "Dockerfile"
          push: true
          tags: ghcr.io/duarte-figueiredo/warehouse:latest,ghcr.io/duarte-figueiredo/warehouse:${{ github.sha }}